export { default as hello } from './hello';
export { default as putTenant } from './tenant/post/create';
export { default as getTenantAdmins } from './tenant/get/admin';
export { default as getTenantUsers } from './tenant/get/user';
export { default as getUserInfo } from './user/get/user';
export { default as getAllTexts } from './text/get/allTexts';
export { default as getTextFromCategory } from './text/get/textFromCategory';
export { default as getTextFromLanguage } from './text/get/textFromLanguage';
export { default as getText } from './text/get/texts';